package com.example.android.emailapp.constants;

public class JsonKeys {

    public static final String VALUE = "value";
    /*client_id: the client ID generated by registering the app.
client_secret: the client secret generated by registering the app.
code: the authorization code obtained in the prior step.
redirect_uri: this value must be the same as the value used in the authorization code request.
grant_type: the type of grant the app is using. For the Authorization Grant Flow, this should always be authorization_code.*/
    public static final String CLIENT_ID = "client_id";
    public static final String CLIENT_SECRET = "client_secret";
    public static final String CODE = "code";
    public static final String REDIRECT_URI = "redirect_uri";
    public static final String GRANT_TYPE = "grant_type";
    public static final String AUTHORIZATION_CODE = "authorization_code";
    public static final String BEARER = "Bearer";
    public static final String ACCESS_TOKEN = "access_token";
    public static final String AUTHORIZATION = "Authorization";
    public static final String MESSAGE = "message";
}
